AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Resources:
  HelloLambda:
    Type: AWS::Serverless::Function
    Properties:
      Handler: streaming_audio_skill
      Runtime: go1.x
      CodeUri: ./deploy/streaming_audio_skill.zip
      Environment:
        Variables: 
          S3_BUCKET: tsbalexaskills
      Events:
        AlexaSkillEvent:
          Type: AlexaSkill
